# Generated by Django 2.0.9 on 2019-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20190616_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rooms', models.PositiveIntegerField()),
                ('bath_rooms', models.PositiveIntegerField()),
                ('building_type', models.CharField(choices=[('R', 'Residential '), ('E', 'Educational '), ('B', 'Business '), ('I', 'Industrial ')], max_length=20)),
                ('parking', models.CharField(max_length=50)),
                ('Furnished', models.CharField(choices=[('F', 'Fully Furnished'), ('P', 'Partly Furnished'), ('N', 'Not Furnished'), ('A', 'Any')], max_length=20)),
                ('detail', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='src/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
